name: sudoku
description: "a sudoku app"
publish_to: "none"
version: 1.1.0+6

environment:
  sdk: ^3.12.1
  flutter: 3.47.0

dependencies:
  cupertino_icons: ^1.0.9
  cupertino_ui: ^1.1.1
  device_info_plus: ^13.2.0
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  hive_ce: ^2.20.0
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.3
  material_ui: ^1.4.0
  package_info_plus: ^10.2.1
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  wakelock_plus: ^1.8.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
