import 'package:sudoku/domain/models/difficulty.dart';
import 'package:sudoku/domain/models/sudoku_grid.dart';

/// Represents a logical hint generated by the Sudoku solving engine.
///
/// This abstraction can represent either a direct digit placement
/// ([DirectHint]) or an indirect candidate elimination ([IndirectHint]). It
/// defines methods to apply the hint to a [SudokuGrid], obtain a localized
/// textual description, and determine its difficulty level.
abstract class Hint {
  /// Base constructor.
  const Hint();

  /// Applies the logical outcome of this hint to update the active [grid]
  /// state.
  void apply(SudokuGrid grid);

  /// Returns a user-friendly, descriptive textual explanation of the hint.
  String description();

  /// Returns the difficulty level of the logical technique used to find this
  /// hint.
  Difficulty getDifficultyLevel();

  /// Returns true if this hint directly fills a value in a cell, false if it
  /// removes candidates.
  bool isPlacement();
}

/// Represents a hint that directly places a solved digit in a cell.
///
/// Direct hints are typically found by simple techniques like Naked Single
/// and Hidden Single.
class DirectHint extends Hint {
  /// Creates a direct digit placement hint.
  const DirectHint(this.cellIndex, this.value, this.difficulty);

  /// The index of the cell that can be solved.
  final int cellIndex;

  /// The correct solved digit value to place.
  final int value;

  /// The logical difficulty of the solving technique.
  final Difficulty difficulty;

  @override
  void apply(SudokuGrid grid) {
    grid.setValue(cellIndex, value);
  }

  @override
  String description() {
    final row = cellIndex ~/ 9 + 1;
    final col = cellIndex % 9 + 1;
    return 'Place $value at ($row,$col)';
  }

  @override
  Difficulty getDifficultyLevel() => difficulty;

  @override
  bool isPlacement() => true;
}

/// Represents a hint that removes one or more candidates from a cell.
///
/// Indirect hints are found by advanced techniques (like Naked/Hidden Pairs,
/// X-Wing, XY-Wing, Swordfish, etc.) that narrow down possibilities.
class IndirectHint extends Hint {
  /// Creates an indirect candidate elimination hint.
  const IndirectHint(this.cellIndex, this.valuesToRemove, this.difficulty);

  /// The index of the cell containing the candidates to eliminate.
  final int cellIndex;

  /// The list of candidate digits to be removed from this cell.
  final List<int> valuesToRemove;

  /// The logical difficulty of the solving technique.
  final Difficulty difficulty;

  @override
  void apply(SudokuGrid grid) {
    for (final value in valuesToRemove) {
      grid.removeCandidate(cellIndex, value);
    }
  }

  @override
  String description() {
    final row = cellIndex ~/ 9 + 1;
    final col = cellIndex % 9 + 1;
    return 'Remove ${valuesToRemove.join(', ')} from candidates at ($row,$col)';
  }

  @override
  Difficulty getDifficultyLevel() => difficulty;

  @override
  bool isPlacement() => false;
}
